# Generated by Django 3.0.3 on 2021-04-22 16:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[users.models.validate_mobile])),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
